# Generated by Django 4.2.6 on 2023-10-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customeraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='order',
            new_name='customer',
        ),
    ]
