# Generated by Django 4.2.6 on 2023-10-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_productrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='Customer',
            new_name='customer',
        ),
    ]
