# Generated by Django 4.2.6 on 2023-11-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_product_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downloads',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
