# Generated by Django 4.2.6 on 2023-11-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
