# Generated by Django 4.2.6 on 2023-11-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_product_published_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_file',
            field=models.FileField(blank=True, null=True, upload_to='product_files/'),
        ),
    ]
